routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

/****   HomePage *****/
Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'home']);

/****   AGENCY  *****/
Route::group(['middleware'=>'roles', 'roles'=> ['agency']], function(){

    //Clients
    Route::resource('client', 'ClientController');

    //Service
    Route::get('/services', ['uses' => 'ServiceController@services', 'as' => 'agency.service.services']);
    Route::get('client/{client_id}/service', ['uses' => 'ServiceController@index', 'as' => 'agency.service.index']);
    Route::get('client/{client_id}/service/{service_id}', ['uses' => 'ServiceController@show', 'as' => 'agency.service.show']);
    Route::post('/change-client', ['uses'=>'ServiceController@changeClient', 'as'=>'service.change.client']);

    //Cart
    Route::get('/cart/{client_id}', ['uses' => 'CartController@index', 'as' => 'cart.index' ]);
    Route::delete('/cart/{client_id}/{id}', ['uses' => 'CartController@destroy', 'as' => 'cart.destroy' ]);

    //Coupon
    Route::post('/cart/check-coupon', ['uses' => 'CartController@checkCoupon', 'as'=> 'cart.check-coupon']);

    //Add to cart Ajax
    Route::post('/addtocart/{client_id}', ['uses' => 'CartController@addToCartAjax', 'as' => 'agency.addtocart' ]);

    //PayPal
    Route::post('/cart/{client_id}/getCheckout', ['as'=>'getCheckout','uses'=>'PaypalController@getCheckout']);
    Route::get('/cart/{client_id}/{order_id}/getDone', ['as'=>'getDone','uses'=>'PaypalController@getDone']);
    Route::get('/cart/{client_id}/{order_id}/getCancel', ['as'=>'getCancel','uses'=>'PaypalController@getCancel']);

    //PayPal Subscription
    Route::post('/cart/{client_id}/payPalSubsription', ['uses'=>'PaypalController@subscription', 'as'=>'paypal.subscribe']);
    Route::get('/cart/{subscription_id}/payPalSubsriptionDone', ['uses'=>'PaypalController@getSubscriptionDone', 'as'=>'paypal.subscribe.done']);
    Route::get('/cart/{subscription_id}/payPalSubsriptionCancel', ['uses'=>'PaypalController@getSubscriptionCancel', 'as'=>'paypal.subscribe.cancel']);

    //Orders
    Route::get('/client/{client_id}/orders', ['uses' => 'OrderController@getClientOrders', 'as' => 'order.orders' ]);
    Route::get('/orders', ['uses' => 'OrderController@index', 'as' => 'order.index' ]);

    //Subscription Orders
    Route::get('/subscriptions', ['uses'=>'SubscriptionController@index', 'as'=>'subscription.index']);
    Route::get('/client/{client_id}/orders/subscriptions', ['uses'=>'SubscriptionController@getClientSubscriptions', 'as'=>'subscription.client']);

    //Deposit
    Route::get('/deposit', ['uses' => 'DepositController@index', 'as' => 'deposit.index' ]);
    Route::post('/deposit/depositCheckout', ['uses'=>'DepositController@depositCheckout', 'as'=>'deposit.Checkout']);
    Route::get('/deposit/depositDone', ['uses'=>'DepositController@depositDone', 'as'=>'depositDone']);
    Route::get('/deposit/depositCancel', ['uses'=>'DepositController@depositCancel', 'as'=>'depositCancel']);
    Route::post('/cart/{client_id}/pay-from-deposit', ['uses'=>'DepositController@payFromDeposit', 'as'=>'cart.deposit']);

    //Transaction
    Route::get('/transactions', ['uses'=>'TransactionController@index', 'as'=>'transaction.index']);

    //Edit User Info
    Route::get('/profile', ['uses'=>'UserController@edit', 'as'=>'user.edit']);
    Route::put('/profile/update', ['uses'=>'UserController@update', 'as'=>'user.update']);
    Route::put('/profile/password-update', ['uses'=>'UserController@passwordUpdate', 'as'=>'password.update']);

    //MESSAGES
    Route::get('/messages', ['uses'=>'MessagesController@index', 'as'=>'messages.index']);
    Route::post('/messages-count', ['uses'=>'MessagesController@newMessagesCount', 'as'=>'messages.count']);

    //MANAGE ACCOUNTS
    Route::get('/manage-accounts', ['uses'=>'ManageAccountsController@index', 'as'=>'manage-accounts']);
    Route::post('/manage-accounts/notes-store', ['uses'=>'ManageAccountsController@notesStore', 'as'=>'manage-accounts.notes-store']);
    Route::post('/manage-accounts/client', ['uses'=>'ManageAccountsController@clientAjax', 'as'=>'manage-accounts.client-ajax']);
    Route::post('/manage-accounts/tags-store', ['uses'=>'ManageAccountsController@tagsStore', 'as'=>'manage-accounts.tags-store']);
    Route::post('/manage-accounts/status-store', ['uses'=>'ManageAccountsController@statusStore', 'as'=>'manage-accounts.status-store']);
    Route::post('/manage-accounts/send-email', ['uses'=>'ManageAccountsController@sendEmail', 'as'=>'manage-accounts.send-email']);

});


/****   ADMIN  *****/
Route::group(['middleware'=>'roles', 'roles'=> ['admin']], function(){

    //ADMIN
    Route::get('/admin', ['uses' => 'Admin\AdminController@index', 'as' => 'admin.index']);

    //SERVICES
    Route::resource('admin/service', 'Admin\ServiceController');

    //CATEGORIES
    Route::resource('admin/categories', 'Admin\CategoryController');

    //OPTIONAL SERVICES
    Route::resource('admin/service-optional', 'Admin\ServiceOptionalController');

    //USERS
    Route::get('admin/agency', ['uses' => 'Admin\UserController@index', 'as' => 'admin.user']);

    //CLIENTS
    Route::get('admin/agency/{agency_id}/clients', ['uses'=>'Admin\ClientController@index', 'as'=>'admin.client']);
    Route::get('admin/agency/{agency_id}/clients/create', ['uses'=>'Admin\ClientController@create', 'as'=>'admin.client.create']);
    Route::post('admin/agency/{agency_id}/clients', ['uses'=>'Admin\ClientController@store', 'as'=>'admin.client.store']);
    Route::get('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@show', 'as'=>'admin.client.show']);
    Route::get('admin/agency/{agency_id}/clients/{client_id}/edit', ['uses'=>'Admin\ClientController@edit', 'as'=>'admin.client.edit']);
    Route::put('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@update', 'as'=>'admin.client.update']);
    Route::delete('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@destroy', 'as'=>'admin.client.destroy']);

    //ORDERS
    //Agency orders
    Route::get('admin/agency/{agency_id}/orders', ['uses'=> 'Admin\OrderController@agency', 'as'=>'admin.order.agency']);
    Route::get('admin/agency/{agency_id}/orders/new', ['uses'=> 'Admin\OrderController@agencyNewOrders', 'as'=>'admin.order.agency.new']);
    Route::get('admin/agency/{agency_id}/orders/active', ['uses'=> 'Admin\OrderController@agencyActiveOrders', 'as'=>'admin.order.agency.active']);
    Route::get('admin/agency/{agency_id}/orders/completed', ['uses'=> 'Admin\OrderController@agencyCompletedOrders', 'as'=>'admin.order.agency.completed']);
    //All orders by group
    Route::get('admin/orders/all', ['uses'=>'Admin\OrderController@orders', 'as'=>'admin.orders.all']);
    Route::get('admin/orders/new', ['uses'=>'Admin\OrderController@newOrders', 'as'=>'admin.orders.new']);
    Route::get('admin/orders/active', ['uses'=>'Admin\OrderController@activeOrders', 'as'=>'admin.orders.active']);
    Route::get('admin/orders/completed', ['uses'=>'Admin\OrderController@completedOrders', 'as'=>'admin.orders.completed']);
    //Ajax update status
    Route::post('admin/orders/change-status', ['uses'=>'Admin\OrderController@changeStatus', 'as'=>'admin.orders.change.status']);
    //Count new Orders
    Route::post('/admin/orders-count', ['uses'=>'Admin\OrderController@newOrdersCount', 'as'=>'admin.orders.count']);

    //Subscriptions
    //Agency Subscriptions
    Route::get('admin/agency/{agency_id}/subscriptions', ['uses'=> 'Admin\SubscriptionController@agency', 'as'=>'admin.subscription.agency']);
    Route::get('admin/agency/{agency_id}/subscriptions/new', ['uses'=> 'Admin\SubscriptionController@agencyNewSubscriptions', 'as'=>'admin.subscription.agency.new']);
    Route::get('admin/agency/{agency_id}/subscriptions/active', ['uses'=> 'Admin\SubscriptionController@agencyActiveSubscriptions', 'as'=>'admin.subscription.agency.active']);
    Route::get('admin/agency/{agency_id}/subscriptions/completed', ['uses'=> 'Admin\SubscriptionController@agencyCompletedSubscriptions', 'as'=>'admin.subscription.agency.completed']);
    //All Subscriptions by Group
    Route::get('admin/subscriptions/all', ['uses'=>'Admin\SubscriptionController@subscriptions', 'as'=>'admin.subscriptions.all']);
    Route::get('admin/subscriptions/new', ['uses'=>'Admin\SubscriptionController@newsubscriptions', 'as'=>'admin.subscriptions.new']);
    Route::get('admin/subscriptions/active', ['uses'=>'Admin\SubscriptionController@activesubscriptions', 'as'=>'admin.subscriptions.active']);
    Route::get('admin/subscriptions/completed', ['uses'=>'Admin\SubscriptionController@completedsubscriptions', 'as'=>'admin.subscriptions.completed']);
    //Ajax update status
    Route::post('admin/subscriptions/change-status', ['uses'=>'Admin\SubscriptionController@changeStatus', 'as'=>'admin.subscriptions.change.status']);
    //Count new Subscriptions
    Route::post('/admin/subscriptions-count', ['uses'=>'Admin\SubscriptionController@newSubscriptionsCount', 'as'=>'admin.subscriptions.count']);

    //COUPONS
    Route::resource('admin/coupons', 'Admin\CouponController');

    //TRANSACTIONS
    Route::get('admin/agency/{agency_id}/transactions', ['uses'=> 'Admin\TransactionController@agency', 'as'=>'admin.transaction.agency']);

    //MESSAGES
    Route::get('/admin/messages/all', ['uses'=>'Admin\MessagesController@threads', 'as'=>'admin.messages.threads']);
    Route::get('/admin/messages/{agency_id}', ['uses'=>'Admin\MessagesController@index', 'as'=>'admin.messages.index']);

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    public function serviceOptionals()
    {
        return $this->hasMany('App\ServiceOptional');
    }

    public function serviceSubscription()
    {
        return $this->hasOne('App\ServiceSubscription');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Image;
use Session;
use Storage;
use App\Service;
use App\ServiceSubscription;
use App\Category;

class ServiceController extends Controller
{
    public function index()
    {
        $services = Service::all();
        return view('admin.service.index')->withServices($services);
    }

    public function create()
    {
        $categories = Category::all();
        return view('admin.service.create')->withCategories($categories);
    }

    public function store(Request $request)
    {
        $service = New Service;

        $service->name = $request->name;
        $service->category_id = $request->category_id;
        $service->price = $request->price;
        $service->old_price = $request->old_price;
        $service->short_description = $request->short_description;
        $service->description = $request->description;
        if ($request->active == 'checked'){
            $service->active = 1;
        }
        else{
            $service->active = 0;
        }
        $service->sort_number = $request->sort_number;

        if ($request->hasfile('image')){
            $image = $request->file('image');
            $filename = time().'.'.$image->getClientOriginalExtension();
            $location = public_path('upload_images/services/'.$filename);
            $img = Image::make($image);
            $img->resize(800, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save($location);

            $service->image = $filename;
        }

        $service->save();

        //Subscription
        if(isset($service->serviceSubscription)){
            if($request->subscription == 1){
                $service->serviceSubscription()->save();
            }
            else{
                $service->serviceSubscription()->delete();
            }
        }
        elseif($request->subscription == 1){
            $serviceSubscription = new ServiceSubscription;
            $serviceSubscription->service()->associate($service);
            $serviceSubscription->save();
        }

        Session::flash('success', 'Service created successfully');

        return redirect()->route('service.show', $service->id);
    }

    public function show($id)
    {
        $service = Service::find($id);
        return view('admin.service.show')->withService($service);
    }

    public function edit($id)
    {
        $service = Service::find($id);
        $categories = Category::all();
        return view('admin.service.edit')->withService($service)->withCategories($categories);
    }

    public function update(Request $request, $id)
    {
        $service = Service::find($id);

        $service->name = $request->name;
        $service->category_id = $request->category_id;
        $service->price = $request->price;
        if(!$request->old_price){
            $service->old_price = $request->price;
        }
        else{
            $service->old_price = $request->old_price;
        }
        $service->short_description = $request->short_description;
        $service->description = $request->description;
        if ($request->active == 'checked'){
            $service->active = 1;
        }
        else{
            $service->active = 0;
        }
        $service->sort_number = $request->sort_number;

        if ($request->hasfile('image')){
            $image = $request->file('image');
            $filename = time().'.'.$image->getClientOriginalExtension();
            $location = public_path('upload_images/services/'.$filename);
            $img = Image::make($image);
            $img->resize(800, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save($location);

            $service->image = $filename;
        }

        $service->save();

        //Subscription
        if(isset($service->serviceSubscription)){
            if($request->subscription == 1){
                $service->serviceSubscription->save();
            }
            else{
                $service->serviceSubscription->delete();
            }
        }
        elseif($request->subscription == 1){
            $serviceSubscription = new ServiceSubscription;
            $serviceSubscription->service()->associate($service);
            $serviceSubscription->save();
        }

        Session::flash('success', 'Service updated successfully');

        return redirect()->route('service.show', $service->id);
    }

    public function destroy($id)
    {
        $service = Service::find($id);

        $location = public_path('upload_images\services\\'.$service->image);

        Storage::delete($location);

        $service->delete();

        Session::flash('success', 'Service was deleted!');

        return redirect()->route('service.index');
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Service;
use App\Client;
use App\Cart;
use App\CartServiceOptional;

class ServiceController extends Controller
{
    public function index($client_id)
    {
        $client = Client::find($client_id);
        $services = Service::orderBy('sort_number', 'asc')->paginate(100);
        return view('agency.service.index')->withServices($services)->withClient($client)->withCart($this->cart($client->id));
    }

    public function show($client_id, $service_id)
    {
        $client = Client::find($client_id);
        $service = Service::find($service_id);
        return view('agency.service.show')->withService($service)->withClient($client)->withCart($this->cart($client->id));
    }

    public function services()
    {
        $services = Service::orderBy('sort_number', 'asc')->paginate(100);
        $client = Client::where('user_id', Auth::user()->id)->first();
        if(isset($client)){
            return view('agency.service.services')->withServices($services)->withClient($client)->withCart($this->cart($client->id));
        }
        else{
            return view('agency.service.no-client-services')->withServices($services);
        }
    }

    public function changeClient(Request $request)
    {

        $cart = Cart::where('client_id', $request->current_client_id)->get();
        foreach ($cart as $cart_item){
            $cart_item->client_id = $request->client_id;
            $cart_item->save();
        }
        return redirect()->route('cart.index', $request->client_id);
    }

    private function cart($client_id){
        $cart = Cart::where('client_id', '=', $client_id)->get();
        return($cart);
    }
}

resources/views/agency/service/index.blade.php
@extends('agency.main')

@section('title', 'All Services')

@section('content')
    <div class="row">
        <div class="col-md-9">
            <h1 class="page-header">
                <span class="glyphicon glyphicon-th-list"></span> All Services
            </h1>
        </div>
    </div>
    <hr>
    <div class="grid">
        @foreach($services as $service)
            <div class="grid-item">
                <div class="thumbnail service-container">
                    <div class="service-header">
                        <div class="service-header-name">{{$service->name}}</div>
                        <div class="service-header-price">
                            <span class="glyphicon glyphicon-usd"></span>
                            {{$service->price}}
                        </div>
                        @if(($service->old_price) && ($service->old_price != $service->price))
                            <div class="service-header-old-price">
                                <span class="glyphicon glyphicon-usd"></span>
                                {{$service->old_price}}
                            </div>
                        @endif
                    </div>
                    <img src="/upload_images/services/{{$service->image}}" >
                    <div class="caption">
                        @if(isset($service->category))
                            <h4><small>Category:<br/></small>{{$service->category->name}}</h4>
                        @endif
                        <div>{!! $service->short_description !!}</div>
                        <hr>
                        <ul data-service-id="{{$service->id}}" class="additional-services">
                            @foreach($service->serviceoptionals as $serviceoptional)
                                <h4>
                                    <strong>{{$serviceoptional->name}}</strong>
                                    @if($serviceoptional->subscription == 1)
                                        <small style="float:right;"></span>Subscription <span class="glyphicon glyphicon-ok"></small>
                                    @endif
                                </h4>
                                @foreach($serviceoptional->serviceOptionalDescriptions as $description)
                                    <div class="checkbox">
                                        <label class="additional-services-label">
                                            <input type="checkbox" class="serviceOptionalDescription" data-service-id="{{$service->id}}" data-id="{{$description->id}}" name="serviceOptionalDescription{{$description->id}}" id="serviceOptionalDescription{{$description->id}}" value="{{$description->id}}" data-price="{{$description->price}}">
                                            {{$description->description}}
                                            <span class="additional-services-span badge"><span class="glyphicon glyphicon-usd"></span> {{$description->price}}</span>
                                        </label>
                                    </div>
                                @endforeach
                                @if($serviceoptional->subscription == 1)
                                    <?php $showSubscription = 1; ?>
                                @endif
                            @endforeach
                        </ul>

                        @if(isset($service->serviceSubscription) || (isset($showSubscription)))
                            <hr>
                            {!! Form::open(['route' => ['paypal.subscribe', $client->id], 'method' => 'post']) !!}
                                <div>
                                    <input type="hidden" name="service_id" value="{{$service->id}}">
                                    <input type="hidden" id="service_optional_ids_{{$service->id}}" name="service_optional_ids" value="">
                                </div>
                                <div style="margin:10px 0;">
                                    <button type="submit" class="btn btn-block btn-success">
                                        <span class="glyphicon glyphicon-usd"></span>
                                        Subscribe with PayPal
                                    </button>
                                    <hr>
                                </div>
                            {!! Form::close() !!}
                        @endif
                        <div class="bottom-buttons">
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="{{ route('agency.service.show', [$client->id, $service->id]) }}" class="btn btn-primary btn-block" role="button">
                                        <span class="glyphicon glyphicon-eye-open"> </span>
                                        Read more
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    <button class="btn btn-success btn-block add-to-cart" role="button" id="{{$service->id}}" data-toggle="modal" data-target="#service-added">
                                        <span class="glyphicon glyphicon-shopping-cart"> </span>
                                        Add to cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>



    <!-- Modal -->
    <div id="service-added" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="bg-success modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Success!</h4>
                </div>
                <div class="modal-body">
                    <p>Service was added to the cart.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
@endsection

@section('stylesheets')
    <style>
        .grid-item{
            width:275px;
            margin-right:20px;
            margin-bottom: 20px;
        }
        .grid{
            width:100%;
        }
    </style>
@endsection

@section('javascript')
    <script src="https://unpkg.com/imagesloaded@4.1/imagesloaded.pkgd.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function(){
            var $grid = $('.grid');
            $grid.imagesLoaded( function(){
                $grid.isotope({
                    layoutMode: 'fitRows',
                    //percentPosition: true,
                    itemSelector: '.grid-item'
                });
            });
        })

    </script>

    <script type="text/javascript">


        //Save checked Optional Serviced ids and send to
        $('.serviceOptionalDescription').on('change', function(){
            var service_id = $(this).attr('data-service-id');
            if(this.checked){
                $('#service_optional_ids_'+service_id).val($('#service_optional_ids_'+service_id).val()+','+$(this).val());
                console.log($('#service_optional_ids_'+service_id).val());
            }
            else{
                var str = $('#service_optional_ids_'+service_id).val().replace($(this).val(), '');
                str = str.replace(/,,/g, ',');
                $('#service_optional_ids_'+service_id).val(str);
                console.log($('#service_optional_ids_'+service_id).val());
            }
        });

        //Close Modal
        $('.add-to-cart').on('click', function(){
            function closeModal() {
                $('#service-added').modal('hide');
            }
            setTimeout(closeModal, 2500);
        });


        //Add Service to the cart
        var url = "{{route('agency.addtocart', $client->id)}}";
        var token = "{{ csrf_token() }}";
        $('.add-to-cart').on('click', function(){
            var id = $(this).attr("id");
            var description_ids = [];
            var total_service_price = 0;
            $('[data-service-id='+id+'] input:checkbox:checked').each(function(){
                description_ids.push($(this).val());
                total_service_price = total_service_price + Number($(this).attr('data-price'));
            });
            console.log(id);
            //console.log(total_service_price);
            console.log(description_ids);
            $.ajax({
                type: "POST",
                url: url,
                data: {id:id, description_ids:description_ids, _token:token},
                success: function(data) {
                    //Inc Cart count
                    var cartCount = $('#cart-count').text();
                    cartCount = Number(cartCount)+1;
                    var service_price=total_service_price+data.service.price;
                    $('#cart-count').html(cartCount);
                    $('.cart-empty').hide();
                    $('.link-to-cart').show();
                    $('.append-before').before('' +
                        '<li>' +
                        '<a href="/services/'+data.service.id+'">' +
                        '<div>' +
                        '<i class="glyphicon glyphicon-check"></i>'+data.service.name+'' +
                        '<span class="pull-right text-muted small">'+service_price+'$</span>' +
                        '</div>' +
                        '</a>' +
                        '</li>');
                    console.log(data);
                }
            });
            $(this).html('<span class="glyphicon glyphicon-shopping-cart"> </span> Added in cart')
        });
    </script>
@endsection

@section('breadcrumbs')
    <div id="breadcrumbs-container">
        <div class="container-small">
            <ol vocab="http://schema.org/" typeof="BreadcrumbList" class="breadcrumbs">
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{route('home')}}">
                        <span property="name">Dashboard</span>
                    </a>
                    <meta property="position" content="1">

                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('client.index') }}">
                        <span property="name">All Clients</span>
                    </a>
                    <meta property="position" content="2">
                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('client.show', $client->id) }}">
                        <span property="name">{{$client->business_name}}</span>
                    </a>
                    <meta property="position" content="3">
                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('agency.service.index', $client->id) }}">
                        <span property="name">All Services</span>
                    </a>
                    <meta property="position" content="4">
                </li>
            </ol>
        </div>
    </div>
@endsection