routes/web.php
    Route::get('client/{client_id}/service', ['uses' => 'ServiceController@index', 'as' => 'agency.service.index']);
    Route::get('client/{client_id}/service/{service_id}', ['uses' => 'ServiceController@show', 'as' => 'agency.service.show']);
    Route::post('/change-client', ['uses'=>'ServiceController@changeClient', 'as'=>'service.change.client']);

    //Cart
    Route::get('/cart/{client_id}', ['uses' => 'CartController@index', 'as' => 'cart.index' ]);
    Route::delete('/cart/{client_id}/{id}', ['uses' => 'CartController@destroy', 'as' => 'cart.destroy' ]);

    //Coupon
    Route::post('/cart/check-coupon', ['uses' => 'CartController@checkCoupon', 'as'=> 'cart.check-coupon']);

    //Add to cart Ajax
    Route::post('/addtocart/{client_id}', ['uses' => 'CartController@addToCartAjax', 'as' => 'agency.addtocart' ]);

    //PayPal
    Route::post('/cart/{client_id}/getCheckout', ['as'=>'getCheckout','uses'=>'PaypalController@getCheckout']);
    Route::get('/cart/{client_id}/{order_id}/getDone', ['as'=>'getDone','uses'=>'PaypalController@getDone']);
    Route::get('/cart/{client_id}/{order_id}/getCancel', ['as'=>'getCancel','uses'=>'PaypalController@getCancel']);

    //PayPal Subscription
    Route::post('/cart/{client_id}/payPalSubsription', ['uses'=>'PaypalController@subscription', 'as'=>'paypal.subscribe']);
    Route::get('/cart/{subscription_id}/payPalSubsriptionDone', ['uses'=>'PaypalController@getSubscriptionDone', 'as'=>'paypal.subscribe.done']);
    Route::get('/cart/{subscription_id}/payPalSubsriptionCancel', ['uses'=>'PaypalController@getSubscriptionCancel', 'as'=>'paypal.subscribe.cancel']);

    //Orders
    Route::get('/client/{client_id}/orders', ['uses' => 'OrderController@getClientOrders', 'as' => 'order.orders' ]);
    Route::get('/orders', ['uses' => 'OrderController@index', 'as' => 'order.index' ]);

    //Subscription Orders
    Route::get('/subscriptions', ['uses'=>'SubscriptionController@index', 'as'=>'subscription.index']);
    Route::get('/client/{client_id}/orders/subscriptions', ['uses'=>'SubscriptionController@getClientSubscriptions', 'as'=>'subscription.client']);

    //Deposit
    Route::get('/deposit', ['uses' => 'DepositController@index', 'as' => 'deposit.index' ]);
    Route::post('/deposit/depositCheckout', ['uses'=>'DepositController@depositCheckout', 'as'=>'deposit.Checkout']);
    Route::get('/deposit/depositDone', ['uses'=>'DepositController@depositDone', 'as'=>'depositDone']);
    Route::get('/deposit/depositCancel', ['uses'=>'DepositController@depositCancel', 'as'=>'depositCancel']);
    Route::post('/cart/{client_id}/pay-from-deposit', ['uses'=>'DepositController@payFromDeposit', 'as'=>'cart.deposit']);

    //Transaction
    Route::get('/transactions', ['uses'=>'TransactionController@index', 'as'=>'transaction.index']);

    //Edit User Info
    Route::get('/profile', ['uses'=>'UserController@edit', 'as'=>'user.edit']);
    Route::put('/profile/update', ['uses'=>'UserController@update', 'as'=>'user.update']);
    Route::put('/profile/password-update', ['uses'=>'UserController@passwordUpdate', 'as'=>'password.update']);

    //MESSAGES
    Route::get('/messages', ['uses'=>'MessagesController@index', 'as'=>'messages.index']);
    Route::post('/messages-count', ['uses'=>'MessagesController@newMessagesCount', 'as'=>'messages.count']);

    //MANAGE ACCOUNTS
    Route::get('/manage-accounts', ['uses'=>'ManageAccountsController@index', 'as'=>'manage-accounts']);
    Route::post('/manage-accounts/notes-store', ['uses'=>'ManageAccountsController@notesStore', 'as'=>'manage-accounts.notes-store']);
    Route::post('/manage-accounts/client', ['uses'=>'ManageAccountsController@clientAjax', 'as'=>'manage-accounts.client-ajax']);
    Route::post('/manage-accounts/tags-store', ['uses'=>'ManageAccountsController@tagsStore', 'as'=>'manage-accounts.tags-store']);
    Route::post('/manage-accounts/status-store', ['uses'=>'ManageAccountsController@statusStore', 'as'=>'manage-accounts.status-store']);
    Route::post('/manage-accounts/send-email', ['uses'=>'ManageAccountsController@sendEmail', 'as'=>'manage-accounts.send-email']);

});


/****   ADMIN  *****/
Route::group(['middleware'=>'roles', 'roles'=> ['admin']], function(){

    //ADMIN
    Route::get('/admin', ['uses' => 'Admin\AdminController@index', 'as' => 'admin.index']);

    //SERVICES
    Route::resource('admin/service', 'Admin\ServiceController');

    //CATEGORIES
    Route::resource('admin/categories', 'Admin\CategoryController');

    //OPTIONAL SERVICES
    Route::resource('admin/service-optional', 'Admin\ServiceOptionalController');

    //USERS
    Route::get('admin/agency', ['uses' => 'Admin\UserController@index', 'as' => 'admin.user']);

    //CLIENTS
    Route::get('admin/agency/{agency_id}/clients', ['uses'=>'Admin\ClientController@index', 'as'=>'admin.client']);
    Route::get('admin/agency/{agency_id}/clients/create', ['uses'=>'Admin\ClientController@create', 'as'=>'admin.client.create']);
    Route::post('admin/agency/{agency_id}/clients', ['uses'=>'Admin\ClientController@store', 'as'=>'admin.client.store']);
    Route::get('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@show', 'as'=>'admin.client.show']);
    Route::get('admin/agency/{agency_id}/clients/{client_id}/edit', ['uses'=>'Admin\ClientController@edit', 'as'=>'admin.client.edit']);
    Route::put('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@update', 'as'=>'admin.client.update']);
    Route::delete('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@destroy', 'as'=>'admin.client.destroy']);

    //ORDERS
    //Agency orders
    Route::get('admin/agency/{agency_id}/orders', ['uses'=> 'Admin\OrderController@agency', 'as'=>'admin.order.agency']);
    Route::get('admin/agency/{agency_id}/orders/new', ['uses'=> 'Admin\OrderController@agencyNewOrders', 'as'=>'admin.order.agency.new']);
    Route::get('admin/agency/{agency_id}/orders/active', ['uses'=> 'Admin\OrderController@agencyActiveOrders', 'as'=>'admin.order.agency.active']);
    Route::get('admin/agency/{agency_id}/orders/completed', ['uses'=> 'Admin\OrderController@agencyCompletedOrders', 'as'=>'admin.order.agency.completed']);
    //All orders by group
    Route::get('admin/orders/all', ['uses'=>'Admin\OrderController@orders', 'as'=>'admin.orders.all']);
    Route::get('admin/orders/new', ['uses'=>'Admin\OrderController@newOrders', 'as'=>'admin.orders.new']);
    Route::get('admin/orders/active', ['uses'=>'Admin\OrderController@activeOrders', 'as'=>'admin.orders.active']);
    Route::get('admin/orders/completed', ['uses'=>'Admin\OrderController@completedOrders', 'as'=>'admin.orders.completed']);
    //Ajax update status
    Route::post('admin/orders/change-status', ['uses'=>'Admin\OrderController@changeStatus', 'as'=>'admin.orders.change.status']);
    //Count new Orders
    Route::post('/admin/orders-count', ['uses'=>'Admin\OrderController@newOrdersCount', 'as'=>'admin.orders.count']);

    //Subscriptions
    //Agency Subscriptions
    Route::get('admin/agency/{agency_id}/subscriptions', ['uses'=> 'Admin\SubscriptionController@agency', 'as'=>'admin.subscription.agency']);
    Route::get('admin/agency/{agency_id}/subscriptions/new', ['uses'=> 'Admin\SubscriptionController@agencyNewSubscriptions', 'as'=>'admin.subscription.agency.new']);
    Route::get('admin/agency/{agency_id}/subscriptions/active', ['uses'=> 'Admin\SubscriptionController@agencyActiveSubscriptions', 'as'=>'admin.subscription.agency.active']);
    Route::get('admin/agency/{agency_id}/subscriptions/completed', ['uses'=> 'Admin\SubscriptionController@agencyCompletedSubscriptions', 'as'=>'admin.subscription.agency.completed']);
    //All Subscriptions by Group
    Route::get('admin/subscriptions/all', ['uses'=>'Admin\SubscriptionController@subscriptions', 'as'=>'admin.subscriptions.all']);
    Route::get('admin/subscriptions/new', ['uses'=>'Admin\SubscriptionController@newsubscriptions', 'as'=>'admin.subscriptions.new']);
    Route::get('admin/subscriptions/active', ['uses'=>'Admin\SubscriptionController@activesubscriptions', 'as'=>'admin.subscriptions.active']);
    Route::get('admin/subscriptions/completed', ['uses'=>'Admin\SubscriptionController@completedsubscriptions', 'as'=>'admin.subscriptions.completed']);
    //Ajax update status
    Route::post('admin/subscriptions/change-status', ['uses'=>'Admin\SubscriptionController@changeStatus', 'as'=>'admin.subscriptions.change.status']);
    //Count new Subscriptions
    Route::post('/admin/subscriptions-count', ['uses'=>'Admin\SubscriptionController@newSubscriptionsCount', 'as'=>'admin.subscriptions.count']);

    //COUPONS
    Route::resource('admin/coupons', 'Admin\CouponController');

    //TRANSACTIONS
    Route::get('admin/agency/{agency_id}/transactions', ['uses'=> 'Admin\TransactionController@agency', 'as'=>'admin.transaction.agency']);

    //MESSAGES
    Route::get('/admin/messages/all', ['uses'=>'Admin\MessagesController@threads', 'as'=>'admin.messages.threads']);
    Route::get('/admin/messages/{agency_id}', ['uses'=>'Admin\MessagesController@index', 'as'=>'admin.messages.index']);
    Route::post('/admin/messages-count', ['uses'=>'Admin\MessagesController@newMessagesCount', 'as'=>'admin.messages.count']);

});

/****   AUTH USERS  *****/
Route::group(['middleware'=>'auth'], function(){

    //MESSAGES
    Route::get('/admin/messages/{agency_id}/all', ['uses'=>'Admin\MessagesController@messages', 'as'=>'admin.messages.all']);
    Route::post('/admin/messages/{agency_id}', ['uses'=>'Admin\MessagesController@store', 'as'=>'admin.messages.store']);
    Route::post('/messages/file-upload/{agency_id}', ['uses'=>'Admin\MessagesController@fileUpload', 'as'=>'messages.fileupload']);
});
//Orders PDF availible for All
Route::get('/orders/pdf-{order_id}', ['uses' => 'OrderController@pdf', 'as' => 'order.pdf' ]);

app/ServiceOptional.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServiceOptional extends Model
{
    public function service()
    {
        return $this->belongsTo('App\Service');
    }

    public function serviceOptionalDescriptions()
    {
        return $this->hasMany('App\ServiceOptionalDescription');
    }
}

app/Http/Controllers/Admin/ServiceOptionalController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Session;
use App\Service;
use App\ServiceOptional;
use App\ServiceOptionalDescription;

class ServiceOptionalController extends Controller
{

    public function index()
    {
        $serviceOptionals = ServiceOptional::all();
        return view('admin.serviceOptional.index')->withServiceoptionals($serviceOptionals);
    }

    public function create()
    {
        $services = Service::all();
        return view('admin.serviceOptional.create')->withServices($services);
    }

    public function store(Request $request)
    {
        $serviceOptional = new ServiceOptional;

        $serviceOptional->name = $request->name;
        $serviceOptional->service_id = $request->service_id;
        $request->subscription == 1 ? $serviceOptional->subscription = 1 : $serviceOptional->subscription = 0;
        $serviceOptional->save();


        for($i=0; $i < count($request->description); $i++){
            $serviceOptionalDescription = new ServiceOptionalDescription;

            $serviceOptionalDescription->serviceOptional()->associate($serviceOptional);
            $serviceOptionalDescription->description = $request->description[$i];
            $serviceOptionalDescription->price = $request->price[$i];
            $serviceOptionalDescription->save();
        }

        Session::flash('success', 'Optional Service created successfully!');

        return redirect()->route('service-optional.index');

    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $services = Service::all();
        $serviceOptional = ServiceOptional::find($id);
        return view('admin.serviceOptional.edit')->withServiceoptional($serviceOptional)->withServices($services);
    }

    public function update(Request $request, $id)
    {
        $serviceOptional = ServiceOptional::find($id);

        $serviceOptional->name = $request->name;
        $serviceOptional->service_id = $request->service_id;
        $request->subscription == 1 ? $serviceOptional->subscription = 1 : $serviceOptional->subscription = 0;
        $serviceOptional->save();
        $serviceOptional->serviceOptionalDescriptions()->delete();


        for($i=0; $i < count($request->description); $i++){
            $serviceOptionalDescription = new ServiceOptionalDescription;

            $serviceOptionalDescription->serviceOptional()->associate($serviceOptional);
            $serviceOptionalDescription->description = $request->description[$i];
            $serviceOptionalDescription->price = $request->price[$i];
            $serviceOptionalDescription->save();
        }

        Session::flash('success', 'Optional Service created successfully!');

        return redirect()->route('service-optional.index');
    }

    public function destroy($id)
    {
        $serviceOptional = ServiceOptional::find($id);
        $serviceOptional->serviceOptionalDescriptions()->delete();
        $serviceOptional->delete();

        Session::flash('success', 'Optional Service was deleted!');

        return redirect()->route('service-optional.index');
    }
}

resources/views/admin/serviceOptional/create.blade.php
@extends('admin.main')

@section('title', 'Create Optional Service')

@section('breadcrumbs')
    <div id="breadcrumbs-container">
        <div class="container-small">
            <ol vocab="http://schema.org/" typeof="BreadcrumbList" class="breadcrumbs">
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{route('home')}}">
                        <span property="name">Dashboard</span>
                    </a>
                    <meta property="position" content="1">
                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('service-optional.index') }}">
                        <span property="name">All Optional Services</span>
                    </a>
                    <meta property="position" content="2">
                </li>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('service-optional.create') }}">
                        <span property="name">Create New Service</span>
                    </a>
                    <meta property="position" content="3">
                </li>

            </ol>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">
                <span class="glyphicon glyphicon-th-list"></span> Create Optional Service
            </h1>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            {!! Form::open(['route' => 'service-optional.store', 'files' => 'true']) !!}

            <label for="service_id">Choose the Service</label>
            <select name="service_id" class="form-control">
                @foreach($services as $service)
                    <option value="{{$service->id}}">{{$service->name}}</option>>
                @endforeach
            </select>

            {{ Form::label('name', 'Name of Optional Service:') }}
            {{ Form::text('name', null, ['class' => 'form-control', 'required' => '']) }}

            {{ Form::label('subscription', 'Subscription:') }}
            {{ Form::checkbox('subscription', 1, null) }}

            <ul class="list-group" style="margin-top:20px;">
                <li class="list-group-item">
                    {{ Form::label('description[]', 'Description [1]:') }}
                    {{ Form::text('description[]', null, ['class' => 'form-control', 'required' => '']) }}

                    {{ Form::label('price[]', 'Price [1]:') }}
                    {{ Form::text('price[]', null, ['class' => 'form-control', 'required' => '']) }}
                </li>
                <li id="list-group-item-last-child" class="list-group-item">
                    <button id="add-new-field" class="btn btn-block btn-primary">Add one more description</button>
                </li>

            </ul>

            <div class="row" style="margin-top:20px;">
                <div class="col-md-6">
                {{ Form::submit('Create Option', ['class' => 'btn btn-success btn-lg btn-block']) }}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>

@endsection

@section('javascript')
    <script>
        var i = 2;
        $('#add-new-field').on('click', function(){
            $('#list-group-item-last-child').before('' +
                '<li class="list-group-item">'+
                    '<label for="description1">Description ['+i+']:</label>' +
                    '<span class="delete-description glyphicon glyphicon glyphicon-remove"></span>'+
                    '<input class="form-control" required="" name="description[]" type="text" id="description['+i+']">'+
                        '<label for="price['+i+']">Price ['+i+']:</label>'+
                    '<input class="form-control" required="" name="price[]" type="text" id="price['+i+']">'+
                '</li>');
            i++;
        });
        $(document).on("click", ".delete-description", function() {
            $(this).parent().remove();
        });
    </script>
@endsection

resources/views/admin/serviceOptional/edit.blade.php
@extends('admin.main')

@section('title', 'Edit'.$serviceoptional->name)

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">
                <span class="glyphicon glyphicon-th-list"></span> Edit {{$serviceoptional->name}}
            </h1>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            {!! Form::model($serviceoptional, ['route' => ['service-optional.update', $serviceoptional->id], 'method' => 'PUT', 'files' => 'true']) !!}

            <label for="service_id">Choose the Service</label>
            <select name="service_id" class="form-control">
                @foreach($services as $service)
                    <option @if($serviceoptional->service->name == $service->name) selected @endif value="{{$service->id}}">{{$service->name}}</option>
                @endforeach
            </select>

            {{ Form::label('name', 'Name of Optional Service:') }}
            {{ Form::text('name', null, ['class' => 'form-control', 'required' => '']) }}

            {{ Form::label('subscription', 'Subscription:') }}
            @if($serviceoptional->subscription == 1)
                <input name="subscription" type="checkbox" value="1" id="subscription" checked>
            @else
                <input name="subscription" type="checkbox" value="1" id="subscription" >
            @endif

            <ul class="list-group" style="margin-top:20px;">
                <li class="list-group-item">
                    @foreach($serviceoptional->serviceOptionalDescriptions as $description)
                    <li class="list-group-item">
                        <label for="description[]">Description [{{ $loop->iteration }}]:</label>
                        @if($loop->iteration > 1)<span class="delete-description glyphicon glyphicon glyphicon-remove"></span>@endif
                        <input class="form-control" required="" name="description[]" value="{{$description->description}}" type="text" id="description[]">

                        <label for="price[]">Price [{{ $loop->iteration }}]:</label>
                        <input class="form-control" required="" name="price[]" value="{{$description->price}}" type="text" id="price[]">
                    </li>
                    @endforeach
                </li>
                <li id="list-group-item-last-child" class="list-group-item">
                    <button id="add-new-field" class="btn btn-block btn-primary">Add one more description</button>
                </li>

            </ul>

            <div class="row" style="margin-top:20px;">
                <div class="col-md-6">
                    {{ Form::submit('Save changes', ['class' => 'btn btn-success btn-lg btn-block']) }}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>

@endsection

@section('breadcrumbs')
    <div id="breadcrumbs-container">
        <div class="container-small">
            <ol vocab="http://schema.org/" typeof="BreadcrumbList" class="breadcrumbs">
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{route('home')}}">
                        <span property="name">Dashboard</span>
                    </a>
                    <meta property="position" content="1">
                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('service-optional.index') }}">
                        <span property="name">All Optional Services</span>
                    </a>
                    <meta property="position" content="2">
                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('service-optional.edit', $serviceoptional->id) }}">
                        <span property="name">Editing {{$serviceoptional->name}}</span>
                    </a>
                    <meta property="position" content="3">
                </li>

            </ol>
        </div>
    </div>
@endsection

@section('javascript')
    <script>
        var i = {{$serviceoptional->serviceOptionalDescriptions->count()}} + 1;
        $('#add-new-field').on('click', function(){
            $('#list-group-item-last-child').before('' +
                '<li class="list-group-item">'+
                '<label for="description1">Description ['+i+']:</label>'+
                '<span class="delete-description glyphicon glyphicon glyphicon-remove"></span>'+
                '<input class="form-control" required="" name="description[]" type="text" id="description['+i+']">'+
                '<label for="price['+i+']">Price ['+i+']:</label>'+
                '<input class="form-control" required="" name="price[]" type="text" id="price['+i+']">'+
                '</li>');
            i++;
        });

        $(document).on("click", ".delete-description", function() {
            $(this).parent().remove();
        });
    </script>
@endsection

resources/views/admin/serviceOptional/index.blade.php
@extends('admin.main')

@section('title', 'All Optional Services')


@section('breadcrumbs')
    <div id="breadcrumbs-container">
        <div class="container-small">
            <ol vocab="http://schema.org/" typeof="BreadcrumbList" class="breadcrumbs">
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{route('home')}}">
                        <span property="name">Dashboard</span>
                    </a>
                    <meta property="position" content="1">
                </li>
                <span> › </span>
                <li property="itemListElement" typeof="ListItem">
                    <a property="item" typeof="WebPage" href="{{ route('service-optional.index') }}">
                        <span property="name">All Optional Services</span>
                    </a>
                    <meta property="position" content="2">
                </li>

            </ol>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-9">
            <h1 class="page-header">
                <span class="glyphicon glyphicon-th-list"></span> All Optional Services
            </h1>
        </div>
        <div class="col-md-3">
            <a href="{{ route('service-optional.create')}}" class="btn btn-lg btn-block btn-primary" style="margin-top:20px;"><span class="glyphicon glyphicon-pencil"> </span> Create new</a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-8">
            @foreach($serviceoptionals as $serviceoptional)
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <strong>{{$serviceoptional->name}} ({{$serviceoptional->service->name}})</strong>
                        @if($serviceoptional->subscription == 1)
                            <small style="float: right">
                                Subscription
                                <span class="glyphicon glyphicon-ok"></span>
                            </small>
                        @endif
                    </div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <ul class="list-group">
                                @foreach($serviceoptional->serviceOptionalDescriptions as $description)
                                    <li class="list-group-item">
                                        <span class="badge"><span class="glyphicon glyphicon-usd"></span> {{$description->price}}</span>
                                        {{$description->description}}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <a class="btn btn-block btn-primary" href="{{route('service-optional.edit', $serviceoptional->id)}}"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                            </div>
                            <div class="col-md-6">
                                {{ Form::open(['route' => ['service-optional.destroy', $serviceoptional->id], 'method' =>'DELETE']) }}
                                <button type="submit" class="btn btn-danger btn-block"><span class="glyphicon glyphicon-trash"> </span> Delete</button>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>

@endsection