routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

/****   HomePage *****/
Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'home']);

/****   AGENCY  *****/
Route::group(['middleware'=>'roles', 'roles'=> ['agency']], function(){

    //Clients
    Route::resource('client', 'ClientController');

    //Service
    Route::get('/services', ['uses' => 'ServiceController@services', 'as' => 'agency.service.services']);
    Route::get('client/{client_id}/service', ['uses' => 'ServiceController@index', 'as' => 'agency.service.index']);
    Route::get('client/{client_id}/service/{service_id}', ['uses' => 'ServiceController@show', 'as' => 'agency.service.show']);
    Route::post('/change-client', ['uses'=>'ServiceController@changeClient', 'as'=>'service.change.client']);

    //Cart
    Route::get('/cart/{client_id}', ['uses' => 'CartController@index', 'as' => 'cart.index' ]);
    Route::delete('/cart/{client_id}/{id}', ['uses' => 'CartController@destroy', 'as' => 'cart.destroy' ]);

    //Coupon
    Route::post('/cart/check-coupon', ['uses' => 'CartController@checkCoupon', 'as'=> 'cart.check-coupon']);

    //Add to cart Ajax
    Route::post('/addtocart/{client_id}', ['uses' => 'CartController@addToCartAjax', 'as' => 'agency.addtocart' ]);

    //PayPal
    Route::post('/cart/{client_id}/getCheckout', ['as'=>'getCheckout','uses'=>'PaypalController@getCheckout']);
    Route::get('/cart/{client_id}/{order_id}/getDone', ['as'=>'getDone','uses'=>'PaypalController@getDone']);
    Route::get('/cart/{client_id}/{order_id}/getCancel', ['as'=>'getCancel','uses'=>'PaypalController@getCancel']);

    //PayPal Subscription
    Route::post('/cart/{client_id}/payPalSubsription', ['uses'=>'PaypalController@subscription', 'as'=>'paypal.subscribe']);
    Route::get('/cart/{subscription_id}/payPalSubsriptionDone', ['uses'=>'PaypalController@getSubscriptionDone', 'as'=>'paypal.subscribe.done']);
    Route::get('/cart/{subscription_id}/payPalSubsriptionCancel', ['uses'=>'PaypalController@getSubscriptionCancel', 'as'=>'paypal.subscribe.cancel']);

    //Orders
    Route::get('/client/{client_id}/orders', ['uses' => 'OrderController@getClientOrders', 'as' => 'order.orders' ]);
    Route::get('/orders', ['uses' => 'OrderController@index', 'as' => 'order.index' ]);

    //Subscription Orders
    Route::get('/subscriptions', ['uses'=>'SubscriptionController@index', 'as'=>'subscription.index']);
    Route::get('/client/{client_id}/orders/subscriptions', ['uses'=>'SubscriptionController@getClientSubscriptions', 'as'=>'subscription.client']);

    //Deposit
    Route::get('/deposit', ['uses' => 'DepositController@index', 'as' => 'deposit.index' ]);
    Route::post('/deposit/depositCheckout', ['uses'=>'DepositController@depositCheckout', 'as'=>'deposit.Checkout']);
    Route::get('/deposit/depositDone', ['uses'=>'DepositController@depositDone', 'as'=>'depositDone']);
    Route::get('/deposit/depositCancel', ['uses'=>'DepositController@depositCancel', 'as'=>'depositCancel']);
    Route::post('/cart/{client_id}/pay-from-deposit', ['uses'=>'DepositController@payFromDeposit', 'as'=>'cart.deposit']);

    //Transaction
    Route::get('/transactions', ['uses'=>'TransactionController@index', 'as'=>'transaction.index']);

    //Edit User Info
    Route::get('/profile', ['uses'=>'UserController@edit', 'as'=>'user.edit']);
    Route::put('/profile/update', ['uses'=>'UserController@update', 'as'=>'user.update']);
    Route::put('/profile/password-update', ['uses'=>'UserController@passwordUpdate', 'as'=>'password.update']);

    //MESSAGES
    Route::get('/messages', ['uses'=>'MessagesController@index', 'as'=>'messages.index']);
    Route::post('/messages-count', ['uses'=>'MessagesController@newMessagesCount', 'as'=>'messages.count']);

    //MANAGE ACCOUNTS
    Route::get('/manage-accounts', ['uses'=>'ManageAccountsController@index', 'as'=>'manage-accounts']);
    Route::post('/manage-accounts/notes-store', ['uses'=>'ManageAccountsController@notesStore', 'as'=>'manage-accounts.notes-store']);
    Route::post('/manage-accounts/client', ['uses'=>'ManageAccountsController@clientAjax', 'as'=>'manage-accounts.client-ajax']);
    Route::post('/manage-accounts/tags-store', ['uses'=>'ManageAccountsController@tagsStore', 'as'=>'manage-accounts.tags-store']);
    Route::post('/manage-accounts/status-store', ['uses'=>'ManageAccountsController@statusStore', 'as'=>'manage-accounts.status-store']);
    Route::post('/manage-accounts/send-email', ['uses'=>'ManageAccountsController@sendEmail', 'as'=>'manage-accounts.send-email']);

});


/****   ADMIN  *****/
Route::group(['middleware'=>'roles', 'roles'=> ['admin']], function(){

    //ADMIN
    Route::get('/admin', ['uses' => 'Admin\AdminController@index', 'as' => 'admin.index']);

    //SERVICES
    Route::resource('admin/service', 'Admin\ServiceController');

    //CATEGORIES
    Route::resource('admin/categories', 'Admin\CategoryController');

    //OPTIONAL SERVICES
    Route::resource('admin/service-optional', 'Admin\ServiceOptionalController');

    //USERS
    Route::get('admin/agency', ['uses' => 'Admin\UserController@index', 'as' => 'admin.user']);

    //CLIENTS
    Route::get('admin/agency/{agency_id}/clients', ['uses'=>'Admin\ClientController@index', 'as'=>'admin.client']);
    Route::get('admin/agency/{agency_id}/clients/create', ['uses'=>'Admin\ClientController@create', 'as'=>'admin.client.create']);
    Route::post('admin/agency/{agency_id}/clients', ['uses'=>'Admin\ClientController@store', 'as'=>'admin.client.store']);
    Route::get('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@show', 'as'=>'admin.client.show']);
    Route::get('admin/agency/{agency_id}/clients/{client_id}/edit', ['uses'=>'Admin\ClientController@edit', 'as'=>'admin.client.edit']);
    Route::put('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@update', 'as'=>'admin.client.update']);
    Route::delete('admin/agency/{agency_id}/clients/{client_id}', ['uses'=>'Admin\ClientController@destroy', 'as'=>'admin.client.destroy']);

    //ORDERS
    //Agency orders
    Route::get('admin/agency/{agency_id}/orders', ['uses'=> 'Admin\OrderController@agency', 'as'=>'admin.order.agency']);
    Route::get('admin/agency/{agency_id}/orders/new', ['uses'=> 'Admin\OrderController@agencyNewOrders', 'as'=>'admin.order.agency.new']);
    Route::get('admin/agency/{agency_id}/orders/active', ['uses'=> 'Admin\OrderController@agencyActiveOrders', 'as'=>'admin.order.agency.active']);
    Route::get('admin/agency/{agency_id}/orders/completed', ['uses'=> 'Admin\OrderController@agencyCompletedOrders', 'as'=>'admin.order.agency.completed']);
    //All orders by group
    Route::get('admin/orders/all', ['uses'=>'Admin\OrderController@orders', 'as'=>'admin.orders.all']);
    Route::get('admin/orders/new', ['uses'=>'Admin\OrderController@newOrders', 'as'=>'admin.orders.new']);
    Route::get('admin/orders/active', ['uses'=>'Admin\OrderController@activeOrders', 'as'=>'admin.orders.active']);
    Route::get('admin/orders/completed', ['uses'=>'Admin\OrderController@completedOrders', 'as'=>'admin.orders.completed']);
    //Ajax update status
    Route::post('admin/orders/change-status', ['uses'=>'Admin\OrderController@changeStatus', 'as'=>'admin.orders.change.status']);
    //Count new Orders
    Route::post('/admin/orders-count', ['uses'=>'Admin\OrderController@newOrdersCount', 'as'=>'admin.orders.count']);

    //Subscriptions
    //Agency Subscriptions
    Route::get('admin/agency/{agency_id}/subscriptions', ['uses'=> 'Admin\SubscriptionController@agency', 'as'=>'admin.subscription.agency']);
    Route::get('admin/agency/{agency_id}/subscriptions/new', ['uses'=> 'Admin\SubscriptionController@agencyNewSubscriptions', 'as'=>'admin.subscription.agency.new']);
    Route::get('admin/agency/{agency_id}/subscriptions/active', ['uses'=> 'Admin\SubscriptionController@agencyActiveSubscriptions', 'as'=>'admin.subscription.agency.active']);
    Route::get('admin/agency/{agency_id}/subscriptions/completed', ['uses'=> 'Admin\SubscriptionController@agencyCompletedSubscriptions', 'as'=>'admin.subscription.agency.completed']);
    //All Subscriptions by Group
    Route::get('admin/subscriptions/all', ['uses'=>'Admin\SubscriptionController@subscriptions', 'as'=>'admin.subscriptions.all']);
    Route::get('admin/subscriptions/new', ['uses'=>'Admin\SubscriptionController@newsubscriptions', 'as'=>'admin.subscriptions.new']);
    Route::get('admin/subscriptions/active', ['uses'=>'Admin\SubscriptionController@activesubscriptions', 'as'=>'admin.subscriptions.active']);
    Route::get('admin/subscriptions/completed', ['uses'=>'Admin\SubscriptionController@completedsubscriptions', 'as'=>'admin.subscriptions.completed']);
    //Ajax update status
    Route::post('admin/subscriptions/change-status', ['uses'=>'Admin\SubscriptionController@changeStatus', 'as'=>'admin.subscriptions.change.status']);
    //Count new Subscriptions
    Route::post('/admin/subscriptions-count', ['uses'=>'Admin\SubscriptionController@newSubscriptionsCount', 'as'=>'admin.subscriptions.count']);

    //COUPONS
    Route::resource('admin/coupons', 'Admin\CouponController');

    //TRANSACTIONS
    Route::get('admin/agency/{agency_id}/transactions', ['uses'=> 'Admin\TransactionController@agency', 'as'=>'admin.transaction.agency']);

    //MESSAGES
    Route::get('/admin/messages/all', ['uses'=>'Admin\MessagesController@threads', 'as'=>'admin.messages.threads']);
    Route::get('/admin/messages/{agency_id}', ['uses'=>'Admin\MessagesController@index', 'as'=>'admin.messages.index']);

resources/views/admin/partials/_footer.blade.php
<footer>

</footer>

resources/views/admin/partials/_head.blade.php
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') - Dashboard</title>
    <!-- Bootstrap Styles-->
    <link href="/admin-assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="/admin-assets/css/font-awesome.css" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="/admin-assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="/admin-assets/css/custom-styles.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="/css/main.css" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    @yield('stylesheets')
</head>

resources/views/admin/partials/_header.blade.php
<nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="head-logo" href="{{ route('home') }}"></a>
        <a class="navbar-brand" style="position:relative; top:3px; left:-20px;" href="{{ route('home') }}">
            Dashboard
        </a>
    </div>

    @if (Auth::user())
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                @if ((Session::has('success')) || (count($errors)>0))
                    <span id="header-message-count">1</span>
                @else
                    <span id="header-message-count"></span>
                @endif
                <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages" id="dropdown-messages">
                @if (Session::has('success'))
                    <li>
                        <a href="#">
                            <div>
                                <strong>Success:</strong>
                                <span class="pull-right text-muted">
                                    <em>Today</em>
                                </span>
                            </div>
                            <div>{{ Session::get('success') }}</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                @endif

                @if (count($errors)>0)
                    <li>
                        <a href="#">
                            <div>
                                <strong>Помилки:</strong>
                                <span class="pull-right text-muted">
                                    <em>Today</em>
                                </span>
                            </div>
                            @foreach ($errors->all() as $error)
                                <div>{{ $error }}</div>
                            @endforeach
                        </a>
                    </li>
                    <li class="divider"></li>
                @endif
                <li>
                    <a class="text-center" href="#">
                        <strong>No System Notifications</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>

            <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                {{--<li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>--}}
                {{--</li>--}}
                {{--<li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                <li>
                    <a href="{{ url('/logout') }}"
                       onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                        <span class="glyphicon glyphicon-log-out"> </span> Logout
                    </a>

                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    @endif
</nav>

resources/views/admin/partials/_javascripts.blade.php
<script>
    window.Laravel = { csrfToken: '{{ csrf_token() }}' };
</script>﻿
<!-- Jquery Js -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Bootstrap Js -->
<script src="/admin-assets/js/bootstrap.min.js"></script>
<!-- Metis Menu Js -->
<script src="/admin-assets/js/jquery.metisMenu.js"></script>
<!-- Morris Chart Js -->
{{--<script src="/admin-assets/js/morris/raphael-2.1.0.min.js"></script>--}}
{{--<script src="/admin-assets/js/morris/morris.js"></script>--}}
{{--<!--Custom Js -->--}}
{{--<script src="/admin-assets/js/custom-scripts.js"></script>--}}
<script>
    (function ($) {
        "use strict";
        var mainApp = {

            initFunction: function () {
                /*MENU
                 ------------------------------------*/
                $('#main-menu').metisMenu();

                $(window).bind("load resize", function () {
                    if ($(this).width() < 768) {
                        $('div.sidebar-collapse').addClass('collapse')
                    } else {
                        $('div.sidebar-collapse').removeClass('collapse')
                    }
                });
            },

            initialization: function () {
                mainApp.initFunction();

            }
        }
        // Initializing ///

        $(document).ready(function () {
            mainApp.initFunction();
        });

    }(jQuery));

    //LISTEN FOR NEW MESSAGE
    var timeout = 1;
    function newMessages(){
        $.ajax({
            url: '{{route('admin.messages.count')}}',
            type:'post',
            data:{timeout:timeout,_token:'{{ csrf_token() }}'},
            success: function(data){
                if(data.count > 0){
                    $('#new-messages-count').text('('+data.count+' new messages)');
                    $('#header-message-count').text(data.count);

                    $('#dropdown-messages').html('' +
                        '<li style="padding:5px 10px;">' +
                        '<div><strong>New Message:</strong></div>' +
                        '<a class="new-message" href="/admin/messages/'+data.message.user_id+'">' +
                        '<strong>'+data.message.message+'</strong>' +
                        '<div><small><span class="glyphicon glyphicon-time"></span>'+data.message.created_at+'</small></div>' +
                        '</a>' +
                        '</li>');
                };
                timeout = timeout+1;
                setTimeout( newMessages(), 10000);
            },
            error: function(data){
                console.log(data);
            }
        });
    };

    newMessages();

    //LISTEN FOR NEW ORDERS
    function newOrders(){
        $.ajax({
            url: '{{route('admin.orders.count')}}',
            type:'post',
            data:{timeout:timeout,_token:'{{ csrf_token() }}'},
            success: function(data){
                if(data.count > 0){
                    $('#orders-count').html('<small>('+data.count+' New Orders)</small>');
                };
                timeout = timeout+1;
                setTimeout( newOrders(), 10000);
            },
            error: function(data){
                console.log(data);
            }
        });
    }

    newOrders();

    //LISTEN FOR NEW SUBSCRIPTIONS
    function newSubscriptions(){
        $.ajax({
            url: '{{route('admin.subscriptions.count')}}',
            type:'post',
            data:{timeout:timeout,_token:'{{ csrf_token() }}'},
            success: function(data){
                if(data.count > 0){
                    $('#subscriptions-count').html('<small>('+data.count+' New Subscriptions)</small>');
                };
                timeout = timeout+1;
                setTimeout( newSubscriptions(), 10000);
            },
            error: function(data){
                console.log(data);
            }
        });
    }

    newSubscriptions();

</script>

@yield('javascript')

resources/views/admin/partials/_sidebar.blade.php
<nav class="navbar-default navbar-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="main-menu">

            <li>
                <a class="{{ Request::is('admin') ? 'active-menu' : '' }}" href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a class="{{ Request::is('admin/service') ? 'active-menu' : '' }}" href="#"><i class="fa fa-sitemap"></i> Services<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('service.index')}}"> All Services</a>
                    </li>
                    <li>
                        <a href="{{route('service-optional.index')}}"> Optional Services</a>
                    </li>
                    <li>
                        <a href="{{route('categories.index')}}"> Categories</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="{{ Request::is('admin/agency') ? 'active-menu' : '' }}" href="{{ route('admin.user') }}"><i class="fa fa-users"></i> Agency</a>
            </li>
            <li>
                <a class="{{ Request::is('admin/coupons') ? 'active-menu' : '' }}" href="{{ route('coupons.index') }}"><i class="glyphicon glyphicon-gift"></i> Coupons</a>
            </li>
            <li>
                <a class="{{ Request::is('admin/orders/all') ? 'active-menu' : '' }}" href="{{ route('admin.orders.all') }}"><i class="fa fa-edit"></i> Orders <span id="orders-count"></span></a>
            </li>
            <li>
                <a class="{{ Request::is('admin/subscriptions/all') ? 'active-menu' : '' }}" href="{{ route('admin.subscriptions.all') }}"><i class="glyphicon glyphicon-signal"></i> Subscriptions <span id="subscriptions-count"></span></a>
            </li>
            <li>
                <a class="{{ Request::is('admin/messages/all') ? 'active-menu' : '' }}" href="{{ route('admin.messages.threads') }}"><i class="fa fa-envelope fa-fw"></i> Messages <small id="new-messages-count"></small></a>
            </li>

        </ul>

    </div>

</nav>